// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdETUhd-SeDM9tW6twkfzScREr-N6HvLA',
    appId: '1:449475197952:web:fb048b3e6b54214222ace5',
    messagingSenderId: '449475197952',
    projectId: 'mis-labs-8f380',
    authDomain: 'mis-labs-8f380.firebaseapp.com',
    storageBucket: 'mis-labs-8f380.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdETUhd-SeDM9tW6twkfzScREr-N6HvLA',
    appId: '1:449475197952:web:3cb6af9eb1dcdc3822ace5',
    messagingSenderId: '449475197952',
    projectId: 'mis-labs-8f380',
    authDomain: 'mis-labs-8f380.firebaseapp.com',
    storageBucket: 'mis-labs-8f380.firebasestorage.app',
  );
}
